###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "coba-elysia@gmail.com",
    "password": "password123",
    "name": "Elysia Tester"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "coba-elysia@gmail.com",
    "password": "password123"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWhrbm50dnYwMDAwdDJ3NGc4eWk1ZWZwIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3NjIyNzE4NjgsImV4cCI6MTc2MjI3MTkyOH0.cZWtuD2wWp9ulJK9qG5TKd3wc-nHXH9coMce6vUsxqE