@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiJjbWk3bzB4em8wMDAwdDI0c3VoM20waWs1IiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNzYzODE2ODE4LCJleHAiOjE3NjM5MDMyMTh9.ZZLm4_01VrForDQFTzeyyx--9IUjLmc8US7NifhlXhc
@hostname = http://localhost:3000

### Ambil semua kategori TASK_KIND
GET {{hostname}}/category?type=TASK_KIND
Authorization: Bearer {{authToken}}

### Buat kategori TASK_TYPE baru
POST {{hostname}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Solo Work",
    "categoryTypeName": "TASK_TYPE"
}

### Ambil semua kategori TASK_TYPE
GET {{hostname}}/category?type=TASK_TYPE
Authorization: Bearer {{authToken}}

### Buat kategori TASK_COLLECTION baru
POST {{hostname}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Zoom Link",
    "categoryTypeName": "TASK_COLLECTION"
}

### Ambil semua kategori TASK_COLLECTION
GET {{hostname}}/category?type=TASK_COLLECTION
Authorization: Bearer {{authToken}}

###
@customCategoryId = cmhl7toig0002t2ekc0r91q11


### Update kategori custom
PUT {{hostname}}/category/{{customCategoryId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Independent Project (Diupdate)"
}

### Ambil TASK_TYPE (untuk melihat hasil update)
GET {{hostname}}/category?type=TASK_TYPE
Authorization: Bearer {{authToken}}

### Hapus kategori custom
DELETE {{hostname}}/category/{{customCategoryId}}
Authorization: Bearer {{authToken}}

### Ambil TASK_TYPE (untuk melihat hasil delete)
GET {{hostname}}/category?type=TASK_TYPE
Authorization: Bearer {{authToken}}

### Buat kategori TASK_KIND baru
POST {{hostname}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Individu",
    "categoryTypeName": "TASK_KIND"
}

### Buat kategori TASK_TYPE baru
POST {{hostname}}/category
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Kelompok",
    "categoryTypeName": "TASK_TYPE"
}

### Uji Validasi Error (INI SEHARUSNYA GAGAL)
GET {{hostname}}/category?type=SALAH_KETIK
Authorization: Bearer {{authToken}}
