@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWhsN2w4dHAwMDAwdDJlazZjZTgwbG02IiwiZW1haWwiOiJjb2JhLWVseXNpYUBnbWFpbC5jb20iLCJpYXQiOjE3NjIyOTk0NjgsImV4cCI6MTc2MjM4NTg2OH0._nKr2KO2HRbwSPy2xEglZjmMw3RgNbQCjAjBlSx1BqE
@hostname = http://localhost:3000

@categoryId_Kind = cmhl7u8hh0006t2ek49rvqslw
@categoryId_Type = cmhlwjuu00005t2q4t444ofgk
@categoryId_Collect = cmhl7tv7l0004t2ekxdm479ed
@categoryId_Update = cmhlwidal0003t2q4i7159uc0

POST {{hostname}}/tasks
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Selesaikan coding task routes (v2 - Many-to-Many)",
    "isCompleted": false,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Type}}",
        "{{categoryId_Collect}}"
    ]
}

###

GET {{hostname}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
@taskId = cmhlwwpai0001t2p8ktjphk99

GET {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}

###

PATCH {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Task routes v2 (DI-UPDATE)",
    "isCompleted": true,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Update}}", 
        "{{categoryId_Collect}}"
    ]
}

###

DELETE {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}

