@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiJjbWk3bzB4em8wMDAwdDI0c3VoM20waWs1IiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNzYzODE2ODE4LCJleHAiOjE3NjM5MDMyMTh9.ZZLm4_01VrForDQFTzeyyx--9IUjLmc8US7NifhlXhc
@hostname = http://localhost:3000

# Makalah
@categoryId_Kind = cmi7o0y0j0002t24sgxrospbu
# Individu
@categoryId_Type = cmi7o0y1k0006t24ss74aby1n
# Drive
@categoryId_Collect = cmi7o0y2d000at24s6dxbf6pg



@categoryId_Update = cmhylpk2y0001t2xotqf0xc7a

POST {{hostname}}/tasks
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Selesaikan makalah",
    "isCompleted": false,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Type}}",
        "{{categoryId_Collect}}"
    ]
}

###

@taskId=cmiab1w2q0001t2uw3g5b5vme

###

#Selesaikan

PATCH {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "isCompleted": true
}

###

GET {{hostname}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{hostname}}/tasks/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

PATCH {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Task routes v2 (DI-UPDATE)",
    "isCompleted": true,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Update}}",
        "{{categoryId_Collect}}"
    ]
}

###

DELETE {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
