@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiJjbWowZnB4Z2cwMDAwdmcwbzlvanN6czlpIiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNzY1Mzk2ODk1LCJleHAiOjE3NjU0ODMyOTV9.5MYUZn_-GwldBu-hY4TTvyRvxb2u8WlXvOMIlywxUrU
@hostname = http://localhost:3000

# Makalah
@categoryId_Kind = cmj0fpxhc0002vg0o0xad4q53
# Individu
@categoryId_Type = cmj0fpxi90006vg0o8jk5l0ns
# Drive
@categoryId_Collect = cmj0fpxj4000avg0ovb1tqzsc


@categoryId_Update = cmhylpk2y0001t2xotqf0xc7a

POST {{hostname}}/tasks
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Selesaikan makalah",
    "isCompleted": false,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Type}}",
        "{{categoryId_Collect}}"
    ]
}

###

@taskId=cmiab1w2q0001t2uw3g5b5vme

###

#Selesaikan

PATCH {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "isCompleted": true
}

###

GET {{hostname}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{hostname}}/tasks/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

PATCH {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Task routes v2 (DI-UPDATE)",
    "isCompleted": true,
    "categoryIds": [
        "{{categoryId_Kind}}",
        "{{categoryId_Update}}",
        "{{categoryId_Collect}}"
    ]
}

###

DELETE {{hostname}}/tasks/{{taskId}}
Authorization: Bearer {{authToken}}
