#!/bin/sh

echo "Running pre-push hook: Linting affected projects..."
pnpm --filter "...[main]" run lint --quiet --max-warnings=0

if [ $? -ne 0 ]; then
  echo "Lint found errors. Push aborted."
  exit 1 
fi

echo "Lint passed. Proceeding with push..."
echo
exit 0